// 手持前置
const a = {
  hardwareLevel: 'limited',
  hasFlash: false,
  hasTorch: false,
  id: '1',
  isMultiCam: false,
  maxExposure: 4,
  maxZoom: 4,
  minExposure: -4,
  minFocusDistance: 10,
  minZoom: 1,
  name: '1 (FRONT) androidx.camera.camera2',
  neutralZoom: 1,
  physicalDevices: ['wide-angle-camera'],
  position: 'front',
  sensorOrientation: 'landscape-right',
  supportsFocus: true,
  supportsLowLightBoost: false,
  supportsRawCapture: false,
};
// 手持前置
const b = {
  hardwareLevel: 'limited',
  hasFlash: true,
  hasTorch: true,
  id: '0',
  isMultiCam: false,
  maxExposure: 4,
  maxZoom: 4,
  minExposure: -4,
  minFocusDistance: 5,
  minZoom: 1,
  name: '0 (BACK) androidx.camera.camera2',
  neutralZoom: 1,
  physicalDevices: ['wide-angle-camera'],
  position: 'back',
  sensorOrientation: 'portrait',
  supportsFocus: true,
  supportsLowLightBoost: false,
  supportsRawCapture: false,
};
// 一加后置
const c = {
  hardwareLevel: 'full',
  hasFlash: true,
  hasTorch: true,
  id: '2',
  isMultiCam: false,
  maxExposure: 18,
  maxZoom: 10,
  minExposure: -18,
  minFocusDistance: 10,
  minZoom: 1,
  name: '2 (BACK) androidx.camera.camera2',
  neutralZoom: 1,
  physicalDevices: ['wide-angle-camera'],
  position: 'back',
  sensorOrientation: 'landscape-right',
  supportsFocus: true,
  supportsLowLightBoost: false,
  supportsRawCapture: false,
};
